"""Builds worker.mjs (what Cloudflare runs) from src/. Run: python3 build.py"""
import json, pathlib
root = pathlib.Path(__file__).parent
html = (root / 'src/index.html').read_text()
i = html.index('const EXTRACT_PROMPT = `') + len('const EXTRACT_PROMPT = `'); j = html.index('`;', i)
prompt = html[i:j]
assert '${' not in prompt and '\\' not in prompt, 'prompt must be plain text'
tpl = (root / 'src/worker-template.js').read_text()
out = '// GENERATED by build.py from src/. Edit src/ and rebuild; do not edit this file.\n' + tpl.replace('__HTML__', json.dumps(html)).replace('__PROMPT__', json.dumps(prompt))
(root / 'worker.mjs').write_text(out)
print('built worker.mjs', len(out), 'bytes')
